### ISSUE TITLE
No points rendered in VPC

### ISSUE THREAD

**Issue by francoisatilio** [PDAL/wrench#19]
When I build a VPC, I get the boundaries display, but at any zoom level the points are never displayed.
On the other hand, creating an overview works and the points in the overview are displayed.
All treatments and renderings work on individual point clouds.
The data used corresponds to the LIDARHD_1-0_LAZ_GR1-0452_6227-2021.7z tile.
geoservices.ign.fr/lidarhd
Uncompressed with 7z, we obtain 4 point clouds in laz format
Semis_2021_0452_6226_LA93_IGN69.laz
Semis_2021_0452_6227_LA93_IGN69.laz
Semis_2021_0453_6226_LA93_IGN69.laz
Semis_2021_0453_6227_LA93_IGN69.laz
Point clouds have no src declared

I've tried:
change laz format to las
the problem is the same

Assigning a projection (EPSG:2154) 
The problem is the same

I've tried a VPC as a temporary file and as a permanent file
The problem is the same
QGis version 3.32
Windows 11 Pro

**Comment by wonder-sk** [comment]
hi @francoisatilio - this is actually a QGIS issue, not a pdal_wrench issue - QGIS currently only shows points when the VPC file references COPC files (or EPT). I have created a ticket in QGIS for that - https://github.com/qgis/QGIS/issues/53765 - and will close this one.

**Comment by francoisatilio** [comment]
Thank you very much. That's good to know, I was beginning to doubt myself :)
