### ISSUE TITLE
Google Colab Version please

### ISSUE THREAD

**Issue by 1kaiser** [PDAL/wrench#2]
colab version with input files support like *.obj *.ply >>> *.glb << anytime soon !🥰🥳🥳🥳

like this >>> https://twitter.com/schl26/status/1635730026673971202
![](https://pbs.twimg.com/media/FrNEpfPXoAInVK5?format=jpg&name=large)

🙏🏻🙏🏻🙏🏻🙏🏻🙏🏻

**Comment by wonder-sk** [comment]
Sorry I don't see how this is related...
