### ISSUE TITLE
Input format

### ISSUE THREAD

**Issue by darrepac** [PDAL/wrench#27]
Hi

I was willing to use the PDAL Thin filtering on a layer with billions of points (just lat/lon coordinate).
Input is either gpkg or geoparquet but none seems supported by the plugin:
![image](https://github.com/PDAL/wrench/assets/7128994/befc0c29-9e7f-4d7a-bf59-d7c3f77f15a5)
Is it normal?

thanks

**Comment by wonder-sk** [comment]
Gpkg or geoparquet are ordinary vector formats, not proper point cloud formats. PDAL does not currently have a reader that would be able to ingest point vector layers. I can imagine at some point PDAL would have `readers.ogr` that would make all sorts of vector formats available to PDAL (https://gdal.org/drivers/vector/index.html)...
