### ISSUE TITLE
filter -> classification==2

### ISSUE THREAD

**Issue by jbbarre** [PDAL/wrench#42]
Hello,
I'm glad to discover pdal_wrench to speed up our PC processing. I'm facing a problem with the TIN generation. I want to create the Tin of a classified point cloud, i.e. create the Digital Terrain Model. I didn't find any parameter in to_raster_tin to filter the point cloud, like --filer=classification==2. Do I miss it ? Is there an alternative to do , via vpc for example ?
If not, it could be a really useful feature to add.
Thanks.

**Comment by wonder-sk** [comment]
hi @jbbarre

All pdal wrench algorithms should support `--filter` option with [PDAL expressions](https://pdal.io/en/stable/stages/expression.html#pdal-expression), so `--filter=Classification==2` as you suggested should work - doesn't it? If something does not work, it is easiest to try running the algorithm from QGIS, which also has a handy expression builder...

**Comment by jbbarre** [comment]
hi, thanks for making time.
Qgis was a good help to find ... a typo. and, it works now.
