### ISSUE TITLE
Proper releases?

### ISSUE THREAD

**Issue by hobu** [PDAL/wrench#8]
Are you guys at the point of making proper releases? To be eligible for inclusion in Conda Forge, the software must have actual releases. I would be happy to manage the Conda Forge feedstock of PDAL wrench.

**Comment by wonder-sk** [comment]
Good idea - I think we are close to doing an initial release. And great to hear you would volunteer to manage the conda package :slightly_smiling_face:

**Comment by wonder-sk** [comment]
https://github.com/PDAL/wrench/releases/tag/v1.0
